name: weight_tracker
description: A flutter project that can be used for tracking change in body weight.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/health
  health: ^1.0.2
  # https://pub.dev/packages/syncfusion_flutter_gauges
  syncfusion_flutter_gauges: ^18.1.43
  #https://pub.dev/packages/flutter_clean_architecture
  flutter_clean_architecture: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/flutter_automation
  #  flutter_automation: ^1.3.2

flutter:
  uses-material-design: true
